export {default as angularLogo} from './assets/images/skills/angular.png'
export {default as graphqlLogo} from './assets/images/skills/graphql.png'
export {default as htmlLogo} from './assets/images/skills/html.png'
export {default as nodeLogo} from './assets/images/skills/node.png'
export {default as reactLogo} from './assets/images/skills/react.png'
export {default as restLogo} from './assets/images/skills/rest.png'
export {default as sassLogo} from './assets/images/skills/sass.png'
export {default as sqlLogo} from './assets/images/skills/sql.png'
export {default as typescriptLogo} from './assets/images/skills/typescript.png'

export {default as firstLevel} from './assets/images/skills/progress/one.png'
export {default as secondLevel} from './assets/images/skills/progress/two.png'
export {default as thirdLevel} from './assets/images/skills/progress/three.png'
export {default as fullLevel} from './assets/images/skills/progress/full.png'

